server:
  port: 8001
  context-path: /client

debug: true

spring:
  aop:
    proxy-target-class: true


security:
  oauth2:
    client:
      accessTokenUri: http://eprupetw0604:9001/server/oauth/token
      userAuthorizationUri: http://eprupetw0604:9001/server/oauth/authorize
      clientId: foo
      clientSecret: foosecret
      serverLogoutUri: http://eprupetw0604:9001/server/customLogout
      clientLogoutUri: http://localhost:8001/client/clientLogout
    resource:
      userInfoUri: http://eprupetw0604:9001/server/auth


logging:
  level:
    org.springframework.security: DEBUG


zuul:
  routes:
    resource:
      path: /resource/**
      url: http://eprupetw0604:8002/resource
    server:
      path: /server/**
      url: http://eprupetw0604:9001/server