debug: true

logging:
  level:
    org.springframework.security: DEBUG

server:
    port: 9001
    wsdl-port: 9005
    context-path: /server

database:
    inMemoryDatabaseTcpPort: 9002
    inMemoryDatabaseWebServerPort: 9003
    driverClass: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9002/~/mydb
    user: sa
    password:

