version: '2' 
services:
  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    container_name: spark-master
    domainname: spark
    networks:
      - spark
    environment:
       MASTER: spark://master:7077
       SPARK_CONF_DIR: /conf
       SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./conf/master:/conf
      - ../spark-streaming-module-web:/opt/web
      - ../spark-streaming-module-jar:/opt/jar
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    container_name: spark-worker
    domainname: spark
    networks:
      - spark
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - "8081:8081"
    volumes:
      - ./conf/worker:/conf

  web-app:
    build: .
    hostname: web-app
    container_name: web-app
    domainname: spark
    networks:
      - spark
    depends_on:
      - spark-worker
    volumes:
      - ../spark-streaming-module-web:/opt/web
      - ../spark-streaming-module-jar:/opt/jar
    ports:
      - "11091:11091"
      - "11092:11092"

networks:
  spark:
    external: true