# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_check_update = false
    config.vm.synced_folder "shared/", "/vagrant", create: true

    (0..2).each do |i|

        config.vm.define "mongod#{i}" do |server|
            server.vm.provider "virtualbox" do |vb|
		        vb.customize ["modifyvm", :id, "--cpus", "2"]
                vb.name = "mongod#{i}-instance"
                vb.memory = 1024
            end
            server.vm.hostname = "mongod#{i}.host.name"
            server.vm.network :private_network, ip: "192.168.12.10#{i}"

            if i == 2
                ENV['INIT_REPLICA'] = "yes"
            else
                ENV['INIT_REPLICA'] = "no"
            end

            server.vm.provision :shell, path: "provision-mongod", env: {"INIT_REPLICA" => ENV['INIT_REPLICA']}
        end
    end
end
