server:
  port: 8001
  context-path: /client

debug: true

spring:
  aop:
    proxy-target-class: true

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    client:
      accessTokenUri: @serverHost@:9001/server/oauth/token
      userAuthorizationUri: @serverHost@:9001/server/oauth/authorize
      clientId: foo
      clientSecret: foosecret
      serverLogoutUri: @serverHost@:9001/server/customLogout
      clientLogoutUri: @serverHost@:8001/client/clientLogout
    resource:
      userInfoUri: @serverHost@:9001/server/auth

zuul:
  routes:
    server:
      path: /server/**
      url: @serverHost@:9001/server